### ISSUE TITLE
recording label and album number? not in CSV

### ISSUE THREAD

**Issue by furshift** [gilphilbert/jblabels#14]
so ive noticed an issue where you can input the label and number into the online studio but in the CSV file they do not show up, as im trying to put them on every label to keep the sleeves and labels together for sorting 500+ records

any ideas why its not showing?

**Comment by gilphilbert** [comment]
Hi, thanks for pointing this out, I have fixed this - the label and number fields will now be included in the CSV. Apologies for the delay
