### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by johnlp66** [gilphilbert/jblabels#3]
If this is not in the correct spot please let me know where to direct. Any previous discussions or thoughts on adding a field for the label and number for example the 45 single for "Africa" (a) and "Good For You" by Toto is on Label COLUMBIA 3335. This would be below the b side title in a different font from the title and artist and would align left to right of center point of the strip itself. 
   
![Screen Shot 2022-06-23 at 4 08 52 PM](https://user-images.githubusercontent.com/108093839/175400179-8c1231ef-5143-46f4-bd11-9babc4d96b2e.png)

**Comment by gilphilbert** [comment]
Apologies for the delay - I've moved house and my development machine has been down for a while. This should be possible - let me look into it

**Comment by gilphilbert** [comment]
OK, so this took waaaaay too long, and I'm sorry about that... but, at last it's done!

I completely rewrote the application so now it's much easier for me to add new features. I also added support for a new font, Merit, that matches closely the font in your example above. Here's the result:

![africa](https://github.com/gilphilbert/jukestudio/assets/3300825/5e5800f8-c106-4b4f-8ac1-6d6c99d3d73c)

Next up is to add support for the "HIT" and "POP" style tags on the arrows in this design

**Comment by gilphilbert** [comment]
...and it's done:

![image](https://github.com/gilphilbert/jukestudio/assets/3300825/637688fe-5f86-487d-abdd-97282e121a49)

If you select the "Arrows" style, you can now add a Genre, which will appear on the right (the word "HIT" will appear on the left)

![Screenshot from 2023-11-12 23-25-49](https://github.com/gilphilbert/jukestudio/assets/3300825/90c64b93-67ad-4a29-8638-0ce2c4438fff)

**Comment by BBJones2024** [comment]
Could you please create a color BLACK -- the shading would be variants of grey.  I have a Black/White/Chrome monochromatic color scheme - and do not want to introduce a "color" into the title cards.  Thanks!

**Comment by gilphilbert** [comment]
I added a new `Monochrome` color scheme for titles, this should do what you're looking for:

![Screenshot from 2024-10-14 22-20-41](https://github.com/user-attachments/assets/8fc5386c-e8c9-4283-91ee-91ab55a4eac8)

**Comment by BBJones2024** [comment]
Perfect!  Thanks so much!

Bob


Bob Jones
SouthLand Films

205|239|8730  T

"Each one of us here today will at one time in our lives look upon a loved one who is in need and ask the same question: We are willing to help, but what, if anything, is needed? For it is true we can seldom help those closest to us. Either we don't know what part of ourselves to give or, more often than not, the part we have to give is not wanted. And so it is those we live with and should know who elude us. But we can still love them - we can love completely without complete understanding." -- A River Runs Through It

________________________________
