### ISSUE TITLE
Print selected labels

### ISSUE THREAD

**Issue by brh5073** [gilphilbert/jblabels#5]
i dont want to reprint all labels every time i need a new label. id like to print just the ones with the check box checked. what is the purpose of the check boxes since it doesnt print the selected ones and you cant delete them?

**Comment by gilphilbert** [comment]
Good question - that's exactly what those select buttons are supposed to do. Let me dig in and find out why it's not only printing the selected labels

**Comment by brh5073** [comment]
Great thanks. I selected the boxes of the labels I wanted to print and it just printed all to a pdf.

**Comment by gilphilbert** [comment]
OK, I've updated the page and tested this on my machine and it works for me. Can you test it and let me know if it works for you? Mass deletion is something else I have planned - at the moment you have to delete the records one at a time with the gray crosses.

**Comment by brh5073** [comment]
Works thanks so much

**Comment by gilphilbert** [comment]
No problem!

**Comment by brh5073** [comment]
Is [this](https://imgur.com/a/SwWlTjj)  the normal print quality or does my printer just suck? Top is an original bottom is what I printed 

I really like your program, just trying to figure everything out

**Comment by gilphilbert** [comment]
The check-marks on the green background? That's called dithering. It's something a printer (or the device driver) usually does when it can't print that exact color - it mixes two colors (in this case white and a darker green) to make the color you want. It's pretty rare these days on modern printers though. I use that style for my jukebox and I don't have that effect on mine, just solid green - so I'd say it's your printer at a guess.

**Comment by brh5073** [comment]
This issue has started again. you can no longer select multiple records and delete/print them
